-- ==============================================================================
-- CLEAN RESET: Drop existing tables to ensure schema matches
-- ==============================================================================
drop table if exists public.trips;
drop table if exists public.companies;
drop table if exists public.car_types;
drop table if exists public.settings;

-- Enable Row Level Security (RLS) for all tables
-- For this initial version, we will allow public read/write access via the anon key.

-- ==============================================================================
-- 1. Trips Table
-- ==============================================================================
create table public.trips (
  trip_id text primary key, -- Changed to TEXT to support custom IDs like VT-2026...
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Core Fields
  company_name text not null,
  booked_by text not null,
  report_to text not null,
  car_type text not null,
  trip_type text not null,
  source text not null,
  destination text not null,
  vehicle_reg_no text not null,
  
  -- Numeric Data
  start_km numeric not null default 0,
  end_km numeric not null default 0,
  total_km numeric not null default 0,
  
  -- Date/Time
  start_date_time timestamp with time zone not null,
  end_date_time timestamp with time zone not null,
  total_time text not null,
  
  -- Costs & Extras
  toll_parking numeric not null default 0,
  additional_km numeric default 0,
  
  -- Signature (Base64)
  signature text
);

alter table public.trips enable row level security;

create policy "Enable all access for anon users on trips"
on public.trips for all to anon using (true) with check (true);

-- ==============================================================================
-- 2. Companies Table
-- ==============================================================================
create table public.companies (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null unique
);

alter table public.companies enable row level security;
create policy "Enable all access for anon users on companies"
on public.companies for all to anon using (true) with check (true);

-- ==============================================================================
-- 3. Car Types Table
-- ==============================================================================
create table public.car_types (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null unique
);

alter table public.car_types enable row level security;
create policy "Enable all access for anon users on car_types"
on public.car_types for all to anon using (true) with check (true);

-- ==============================================================================
-- 4. Settings Table
-- ==============================================================================
create table public.settings (
  key text primary key,
  value text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.settings enable row level security;
create policy "Enable all access for anon users on settings"
on public.settings for all to anon using (true) with check (true);

-- ==============================================================================
-- Initial Data Seeding
-- ==============================================================================

insert into public.companies (name) values ('Vista Travels HQ');
insert into public.car_types (name) values ('Sedan'), ('SUV'), ('Innova'), ('Crysta'), ('Tempo Traveller');

insert into public.settings (key, value) values
('agencyName', 'Vista Travels'),
('addressLine1', 'No. 51, Brodies Road, Karayanchavadi,'),
('addressLine2', 'Poonamallee, Chennai - 600056'),
('contactNumber', '+91 98400 12345'),
('email', 'bookings@vistatravels.com');
