-- Enable Row Level Security (RLS) for all tables
-- For this initial version, we will allow public read/write access via the anon key.
-- IMPORTANT: In a production environment with multi-tenancy, these policies should be restricted.

-- ==============================================================================
-- 1. Trips Table
-- ==============================================================================
create table if not exists public.trips (
  trip_id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Core Fields
  company_name text not null,
  booked_by text not null,
  report_to text not null,
  car_type text not null,
  trip_type text not null,
  source text not null,
  destination text not null,
  vehicle_reg_no text not null,
  
  -- Numeric Data
  start_km numeric not null default 0,
  end_km numeric not null default 0,
  total_km numeric not null default 0,
  
  -- Date/Time
  start_date_time timestamp with time zone not null,
  end_date_time timestamp with time zone not null,
  total_time text not null, -- Stored as string to match "HH:mm" or "Xh Ym" format
  
  -- Costs & Extras
  toll_parking numeric not null default 0,
  additional_km numeric default 0,
  
  -- Signature (Base64)
  signature text
);

alter table public.trips enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies 
    where schemaname = 'public' 
    and tablename = 'trips' 
    and policyname = 'Enable all access for anon users on trips'
  ) then
    create policy "Enable all access for anon users on trips"
    on public.trips for all
    to anon
    using (true)
    with check (true);
  end if;
end $$;

-- ==============================================================================
-- 2. Companies Table (Dropdown Data)
-- ==============================================================================
create table if not exists public.companies (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null unique
);

alter table public.companies enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies 
    where schemaname = 'public' 
    and tablename = 'companies' 
    and policyname = 'Enable all access for anon users on companies'
  ) then
    create policy "Enable all access for anon users on companies"
    on public.companies for all
    to anon
    using (true)
    with check (true);
  end if;
end $$;

-- ==============================================================================
-- 3. Car Types Table (Dropdown Data)
-- ==============================================================================
create table if not exists public.car_types (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null unique
);

alter table public.car_types enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies 
    where schemaname = 'public' 
    and tablename = 'car_types' 
    and policyname = 'Enable all access for anon users on car_types'
  ) then
    create policy "Enable all access for anon users on car_types"
    on public.car_types for all
    to anon
    using (true)
    with check (true);
  end if;
end $$;

-- ==============================================================================
-- 4. Settings Table (Key-Value Configuration)
-- ==============================================================================
create table if not exists public.settings (
  key text primary key,
  value text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.settings enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies 
    where schemaname = 'public' 
    and tablename = 'settings' 
    and policyname = 'Enable all access for anon users on settings'
  ) then
    create policy "Enable all access for anon users on settings"
    on public.settings for all
    to anon
    using (true)
    with check (true);
  end if;
end $$;

-- ==============================================================================
-- Initial Data Seeding
-- ==============================================================================

-- Seed Default Companies
insert into public.companies (name) values
('Vista Travels HQ')
on conflict (name) do nothing;

-- Seed Default Car Types
insert into public.car_types (name) values
('Sedan'),
('SUV'),
('Innova'),
('Crysta'),
('Tempo Traveller')
on conflict (name) do nothing;

-- Seed Default Settings
insert into public.settings (key, value) values
('agencyName', 'Vista Travels'),
('addressLine1', 'No. 51, Brodies Road, Karayanchavadi,'),
('addressLine2', 'Poonamallee, Chennai - 600056'),
('contactNumber', '+91 98400 12345'),
('email', 'bookings@vistatravels.com')
on conflict (key) do nothing;
